/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Java library project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.14.1/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    `java-library`
    `maven-publish`
}


repositories {
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    // Use JUnit Jupiter for testing.
    testImplementation(libs.junit.jupiter)
    implementation("org.bouncycastle:bcprov-jdk18on:1.81")
    testRuntimeOnly("org.junit.platform:junit-platform-launcher")

    // This dependency is exported to consumers, that is to say found on their compile classpath.
    api(libs.commons.math3)

    // This dependency is used internally, and not exposed to consumers on their own compile classpath.
    implementation(libs.guava)
    implementation(libs.bouncycastle)
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(8)
    }
}

tasks.named<Test>("test") {
    // Use JUnit Platform for unit tests.
    useJUnitPlatform()
}

tasks.jar {
    archiveBaseName.set("crypto")
    archiveVersion.set("1.0.1")
}

publishing {
    publications {
        create<MavenPublication>("maven") {
            groupId = "me.totoku103"
            artifactId = "crypto"
            version = "1.0.1"

            from(components["java"])
        }
    }

    repositories {
        maven {
            name = "Local"
            url = uri("file:///Users/totoku103/Totoku103Projects/totoku103-maven-repository/releases")
        }
    }
}

// GitHub에 자동 배포하는 태스크
tasks.register("publishToGitHub") {
    group = "publishing"
    description = "Publish to local Maven repository and push to GitHub"

    dependsOn("publishMavenPublicationToLocalRepository")

    doLast {
        val repoPath = "/Users/totoku103/Totoku103Projects/totoku103-maven-repository/releases"
        val version = "1.0.1"

        exec {
            workingDir = file(repoPath)
            commandLine("git", "add", "me/")
        }

        exec {
            workingDir = file(repoPath)
            commandLine("git", "commit", "-m", "Deploy me.totoku103:crypto:$version")
        }

        exec {
            workingDir = file(repoPath)
            commandLine("git", "push")
        }

        println("\n✅ Successfully published to GitHub!")
        println("📦 Repository: https://github.com/totoku103/totoku103-maven-repository")
    }
}